apiVersion: v1
kind: ConfigMap
metadata:
  name: fluentd-config
  namespace: unicorn
data:
  fluent.conf: |
    <source>
      @type forward
      port 24224
      bind 0.0.0.0
    </source>

    <filter book.**>
      @type grep
      <exclude>
        key log
        pattern /health/
      </exclude>
    </filter>

    <filter book.**>
      @type parser
      key_name log
      reserve_data false
      <parse>
        @type regexp
        expression /^(?<timestamp>\S+ \S+) access method=(?<method>\S+) path=(?<path>\S+) status=(?<status_code>\d+) duration=\S+ remote_addr=(?<client_ip>[^:]+):\d+ user_agent=.*$/
        types status_code:integer
      </parse>
    </filter>

    <filter book.**>
      @type record_transformer
      enable_ruby true
      <record>
        timestamp ${require 'time'; Time.strptime(record["timestamp"], "%Y/%m/%d %H:%M:%S").utc.strftime("%Y-%m-%dT%H:%M:%SZ")}
      </record>
    </filter>

    <match book.**>
      @type cloudwatch_logs
      log_group_name /unicorn/eks/book-app
      auto_create_stream true
      use_tag_as_stream true
      json_handler yajl
      <buffer>
        flush_interval 5s
      </buffer>
    </match>
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: fluentd
  namespace: unicorn
spec:
  replicas: 1
  selector:
    matchLabels:
      component: fluentd
  template:
    metadata:
      labels:
        component: fluentd
    spec:
      nodeSelector:
        unicorn: addon
      serviceAccountName: unicorn-book-app-sa
      containers:
      - name: fluentd
        image: fluent/fluentd-kubernetes-daemonset:v1-debian-cloudwatch
        env:
        - name: AWS_REGION
          value: "ap-northeast-2"
        ports:
        - containerPort: 24224
          protocol: TCP
        volumeMounts:
        - name: config
          mountPath: /fluentd/etc/
      volumes:
      - name: config
        configMap:
          name: fluentd-config
---
apiVersion: v1
kind: Service
metadata:
  name: fluentd
  namespace: unicorn
spec:
  selector:
    component: fluentd
  ports:
  - port: 24224
    targetPort: 24224
    protocol: TCP
