FROM golang:1.22-alpine AS builder
WORKDIR /src
COPY go.mod go.sum ./
RUN go mod download
COPY . .
RUN CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build -o /user ./user/

FROM gcr.io/distroless/static-debian12
COPY --from=builder /user /user
EXPOSE 8080
ENTRYPOINT ["/user"]
