# =============================================================================
# Addon Load Balancer (wsc-addon-lb) - Public ALB
#  - /grafana -> grafana svc, /prometheus -> prometheus-server svc
#   ${ADDON_LB_SUBNETS} : public-a,public-c subnet id
# =============================================================================
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: wsc-addon-ingress
  namespace: monitoring
  annotations:
    alb.ingress.kubernetes.io/load-balancer-name: wsc-addon-lb
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/target-type: ip
    alb.ingress.kubernetes.io/subnets: ${ADDON_LB_SUBNETS}
    alb.ingress.kubernetes.io/listen-ports: '[{"HTTP":80}]'
    alb.ingress.kubernetes.io/healthcheck-path: /grafana/api/health
    alb.ingress.kubernetes.io/success-codes: "200,302"
spec:
  ingressClassName: alb
  rules:
    - http:
        paths:
          - path: /grafana
            pathType: Prefix
            backend:
              service:
                name: grafana
                port:
                  number: 80
          - path: /prometheus
            pathType: Prefix
            backend:
              service:
                name: prometheus-server
                port:
                  number: 80
